openapi: 3.0.0
info:
  title: Taskly API Documentation
  version: 1.0.0
paths:
  /api/auth/register:
    post:
      summary: Sign up a new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                organization:
                  type: string
      responses:
        "201":
          description: Registration successful
        "400":
          description: Invalid input, please check the provided data

  /api/auth/login:
    post:
      summary: Authenticate user login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
        "401":
          description: Unauthorized, incorrect credentials

  /api/organizations/{organizationId}/boards:
    post:
      summary: Create a board within an organization
      tags:
        - Board
      parameters:
        - in: path
          name: organizationId
          required: true
          schema:
            type: string
          description: The ID of the organization to create the board in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the board to create
                description:
                  type: string
                  description: Details about the board
      responses:
        "201":
          description: Board successfully created within the organization
        "401":
          description: Unauthorized access, please authenticate
        "400":
          description: Bad request, check input data

    get:
      summary: Get all boards within an organization
      tags:
        - Board
      parameters:
        - in: path
          name: organizationId
          required: true
          schema:
            type: string
          description: The ID of the organization to retrieve boards from
      responses:
        "200":
          description: List of boards within the organization
        "401":
          description: Unauthorized access, please authenticate
        "404":
          description: Organization not found
        "400":
          description: Bad request, check input data

  /api/boards/{id}:
    get:
      summary: Get a specific board by ID
      tags:
        - Board
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the board to retrieve
      responses:
        "200":
          description: Successfully retrieved the board
        "401":
          description: Unauthorized access, please authenticate
        "404":
          description: Board not found
        "400":
          description: Bad request, check input data

    put:
      summary: Update a specific board by ID
      tags:
        - Board
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the board to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The updated name of the board
                description:
                  type: string
                  description: The updated details of the board
      responses:
        "200":
          description: Board successfully updated
        "401":
          description: Unauthorized access, please authenticate
        "404":
          description: Board not found
        "400":
          description: Bad request, check input data

    delete:
      summary: Delete a specific board by ID
      tags:
        - Board
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the board to delete
      responses:
        "204":
          description: Board successfully deleted
        "401":
          description: Unauthorized access, please authenticate
        "404":
          description: Board not found

  /api/boards/{boardId}/tasks:
    post:
      summary: Create a task in a specific board
      tags:
        - Task
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
          description: The ID of the board to create the task in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the task
                description:
                  type: string
                  description: Details of the task
      responses:
        "201":
          description: Task successfully created
        "401":
          description: Unauthorized access, please authenticate
        "400":
          description: Bad request, check input data

    get:
      summary: Get all tasks in a specific board
      tags:
        - Task
      parameters:
        - in: path
          name: boardId
          required: true
          schema:
            type: string
          description: The ID of the board to retrieve tasks from
      responses:
        "200":
          description: List of tasks within the board
        "401":
          description: Unauthorized access, please authenticate
        "404":
          description: Board not found
        "400":
          description: Bad request, check input data

  /api/tasks/{taskId}:
    get:
      summary: Get a specific task by ID
      tags:
        - Task
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
          description: The ID of the task to retrieve
      responses:
        "200":
          description: Successfully retrieved the task
        "401":
          description: Unauthorized access, please authenticate
        "404":
          description: Task not found
        "400":
          description: Bad request, check input data

    put:
      summary: Update a specific task by ID
      tags:
        - Task
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
          description: The ID of the task to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The updated title of the task
                description:
                  type: string
                  description: The updated details of the task
      responses:
        "200":
          description: Task successfully updated
        "401":
          description: Unauthorized access, please authenticate
        "404":
          description: Task not found
        "400":
          description: Bad request, check input data

    delete:
      summary: Delete a specific task by ID
      tags:
        - Task
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
          description: The ID of the task to delete
      responses:
        "204":
          description: Task successfully deleted
        "401":
          description: Unauthorized access, please authenticate
        "404":
          description: Task not found
