openapi: 3.0.0
info:
  title: Taskly API
  version: 1.0.0
paths:
  /api/auth/register:
    post:
      summary: Register a user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                organization:
                  type: string
      responses:
        "201":
          description: User registered
        "400":
          description: Bad request
  /api/auth/login:
    post:
      summary: Login a user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User logged in
        "401":
          description: Unauthorized
  /api/organizations:
    post:
      summary: Create an organization
      tags:
        - Organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the organization
                description:
                  type: string
                  description: Description of the organization
      responses:
        "201":
          description: Organization Created Success
        "401":
          description: Unauthorized
        "404":
          description: Organization not found
        "400":
          description: Bad request
  /api/{organizationId}/addUser:
    post:
      summary: Add a user to an oraganization
      tags:
        - Organization
      parameters:
        - in: path
          name: organizationId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The id of the user to added to an organization
      responses:
        "201":
          description: User added to an organization
        "401":
          description: Unauthorized
        "404":
          description: User not found
        "400":
          description: Bad request
